// #region Firmware generation
// The board already knows its own pinout, so the firmware should never retype
// it. Every net that lands on an MCU pin becomes a named constant, regenerated
// from the netlist whenever the schematic changes. Rename a net, rebuild the
// header, and the code follows.

import type { Schematic } from "./schematic";
import { buildNetlist, type Netlist, type DefResolver } from "./netlist";
import { mcuProfileFor, type McuProfile } from "./mcu";

export interface FirmwarePin {
  net: string;
  symbol: string; // C identifier
  gpio: number;
  pinNumber: string;
  note?: string;
  strapping?: string;
  adc?: { unit: 1 | 2; channel: number };
}

export interface FirmwareTarget {
  ref: string;
  profile: McuProfile;
  pins: FirmwarePin[];
}

// "ESTOP1_RAW" from "estop1-raw", "N$3" from "N$3", etc.
export function toIdentifier(net: string): string {
  // Keep the polarity that differential and rail names carry: USB_D+ and USB_D-
  // must not both collapse to PIN_USB_D.
  let s = net.trim().toUpperCase().replace(/\+/g, "_P").replace(/-/g, "_N");
  s = s.replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  if (!s) s = "NET";
  if (/^[0-9]/.test(s)) s = `N_${s}`;
  return `PIN_${s}`;
}

export function firmwareTargets(schem: Schematic, resolve?: DefResolver, netlist?: Netlist): FirmwareTarget[] {
  const nl = netlist ?? buildNetlist(schem, resolve);
  const out: FirmwareTarget[] = [];
  for (const inst of schem.symbols) {
    const profile = mcuProfileFor(inst.libId);
    if (!profile) continue;
    const ref = inst.properties.Reference ?? "?";
    const pins: FirmwarePin[] = [];
    const used = new Set<string>();
    for (const mp of profile.pins) {
      if (mp.gpio === undefined) continue;
      const net = nl.netOfPin[`${ref}:${mp.number}`];
      if (!net) continue;
      const netObj = nl.nets.find((n) => n.name === net);
      // Power rails and stubs are not firmware pins.
      if (!netObj || netObj.isPower || netObj.pins.length < 2) continue;
      let symbol = toIdentifier(net);
      while (used.has(symbol)) symbol = `${symbol}_${mp.gpio}`;
      used.add(symbol);
      pins.push({
        net,
        symbol,
        gpio: mp.gpio,
        pinNumber: mp.number,
        note: mp.note,
        strapping: mp.strapping,
        adc: mp.adc,
      });
    }
    out.push({ ref, profile, pins: pins.sort((a, b) => a.gpio - b.gpio) });
  }
  return out;
}

export function generatePinsHeader(target: FirmwareTarget): string {
  const lines: string[] = [
    "// Generated by loon from the schematic. Do not edit by hand:",
    "// rename the net on the sheet and this file is rebuilt from it.",
    `// Target: ${target.profile.name} (${target.ref})`,
    "",
    "#pragma once",
    "",
  ];
  for (const p of target.pins) {
    const notes = [p.note, p.strapping ? `strapping pin: ${p.strapping}` : "", p.adc ? `ADC${p.adc.unit} channel ${p.adc.channel}` : ""]
      .filter(Boolean)
      .join("; ");
    if (notes) lines.push(`// ${p.net}: ${notes}`);
    lines.push(`#define ${p.symbol} ${p.gpio}  // net ${p.net}, package pin ${p.pinNumber}`);
  }
  if (target.pins.length === 0) lines.push("// No MCU pins are wired to anything yet.");
  lines.push("");
  lines.push("// Rules that apply to this part:");
  for (const r of target.profile.rules) lines.push(`//  - ${r}`);
  lines.push("");
  return lines.join("\n");
}

export function generatePlatformIni(target: FirmwareTarget): string {
  const isS3 = target.profile.libId.includes("S3");
  return [
    "; Generated by loon. Edit freely: it is only written when missing.",
    "[env:board]",
    "platform = espressif32",
    `board = ${isS3 ? "esp32-s3-devkitc-1" : "esp32dev"}`,
    "framework = arduino",
    "monitor_speed = 115200",
    "build_flags =",
    "    -DARDUINO_USB_CDC_ON_BOOT=1",
    "    -DARDUINO_USB_MODE=1",
    "",
    "; Build used by the simulator only. It targets the classic ESP32 because",
    "; the prebuilt Arduino libraries for the S3 put their console on",
    "; USB-Serial-JTAG, which the emulator does not model - an S3 sketch asserts",
    "; during startup before it reaches loop(). Same source, same GPIO numbers",
    "; from board_pins.h; only the console differs. Pins above GPIO39 do not",
    "; exist on the classic part, so treat this build as a behaviour bench, not",
    "; a substitute for the real board.",
    "[env:sim]",
    "platform = espressif32",
    "board = esp32dev",
    "framework = arduino",
    "monitor_speed = 115200",
    "",
  ].join("\n");
}

export function generateMainStub(target: FirmwareTarget): string {
  const first = target.pins[0];
  return `// Starter firmware generated by loon. Ask the assistant to write the real
// logic; the pin names below come from the schematic.
#include <Arduino.h>
#include "board_pins.h"

void setup() {
  Serial.begin(115200);
  delay(200);
  Serial.println("${target.profile.name} up");
${target.pins
  .slice(0, 8)
  .map((p) => `  Serial.printf("${p.net} = GPIO%d\\n", ${p.symbol});`)
  .join("\n")}
}

void loop() {
${first ? `  // ${first.net} is on GPIO${first.gpio}` : "  // no pins wired yet"}
  // The board's watchdog is fed by this line: the simulator treats a KICK as
  // proof the firmware is alive, exactly as the hardware treats the kick pin.
  Serial.println("KICK");
  delay(250);
}
`;
}
