// #region SPICE
// Turns the schematic into a netlist ngspice can run. Only parts with a model
// are emitted; anything else is listed as unmodelled rather than guessed at,
// because a simulation that silently drops a part is worse than no simulation.
//
// The nets come from the same engine the board and the ERC use, so what gets
// simulated is what is actually wired.

import type { Schematic } from "./schematic";
import { buildNetlist, type Netlist, type DefResolver } from "./netlist";

export type AnalysisKind = "tran" | "dc" | "ac" | "op";

export interface SpiceSource {
  // Net to drive, and how.
  net: string;
  kind: "dc" | "pulse" | "sin" | "pwl";
  // DC level, or the parameters of the waveform.
  dc?: number;
  pulse?: { v1: number; v2: number; delay: number; rise: number; fall: number; width: number; period: number };
  sin?: { offset: number; amplitude: number; freq: number };
  pwl?: { t: number; v: number }[];
}

export interface SpiceBench {
  name: string;
  analysis: AnalysisKind;
  // tran: stop time and step, in seconds.
  tranStop?: number;
  tranStep?: number;
  // dc: sweep source name, start, stop, step.
  dcSweep?: { source: string; start: number; stop: number; step: number };
  ac?: { points: number; start: number; stop: number };
  sources: SpiceSource[];
  // Nets to record.
  probes: string[];
  // Extra raw SPICE lines, the escape hatch.
  extra?: string[];
}

export interface SpiceDeck {
  text: string;
  unmodelled: { ref: string; libId: string; reason: string }[];
  nets: string[];
}

// Value strings from the schematic ("10k", "100n", "4.7u") are already SPICE
// syntax apart from the odd unit suffix.
function spiceValue(raw: string | undefined, fallback: string): string {
  if (!raw) return fallback;
  const v = raw.trim().replace(/\s*(ohm|ohms|Ω|F|H)\b/gi, "").replace(/µ/g, "u");
  const m = v.match(/^([\d.]+)\s*([a-zA-Z]*)/);
  if (!m) return fallback;
  const [, num, suffix] = m;
  const s = suffix.toLowerCase();
  const map: Record<string, string> = { k: "k", m: "m", u: "u", n: "n", p: "p", meg: "meg", g: "g", r: "" };
  return `${num}${map[s] ?? ""}`;
}

// Models for the discrete parts loon places. ICs need a vendor subcircuit,
// which is why they are reported instead of invented.
const DIODE_MODELS: Record<string, string> = {
  BAT54: ".model DSCHOTTKY D(IS=1e-7 RS=2 N=1.05 CJO=10p BV=30)",
  B560C: ".model DPOWER D(IS=2e-5 RS=0.02 N=1.05 CJO=300p BV=60)",
  LED: ".model DLED D(IS=1e-20 N=2.0 RS=5)",
  DEFAULT: ".model DDEFAULT D(IS=1e-14 RS=0.5 N=1.3 BV=75)",
};

const NMOS_MODEL = ".model NMOSSW NMOS(VTO=1.8 KP=2 LAMBDA=0.01)";
const NPN_MODEL = ".model NPNGEN NPN(BF=200 IS=1e-14 VAF=100)";

function diodeModelFor(value: string): string {
  const v = (value || "").toUpperCase();
  if (v.includes("BAT54") || v.includes("SCHOTTKY")) return "DSCHOTTKY";
  if (v.includes("B560") || v.includes("SS3") || v.includes("SS5")) return "DPOWER";
  if (v.includes("LED")) return "DLED";
  return "DDEFAULT";
}

export function buildSpiceDeck(
  schem: Schematic,
  bench: SpiceBench,
  resolve?: DefResolver,
  netlist?: Netlist,
): SpiceDeck {
  const nl = netlist ?? buildNetlist(schem, resolve);
  const unmodelled: { ref: string; libId: string; reason: string }[] = [];
  const lines: string[] = [`* ${bench.name} - generated by loon`];

  // SPICE wants node names without awkward characters, and node 0 is ground.
  const nodeName = (net: string | undefined): string => {
    if (!net) return "0";
    if (/^(gnd|agnd|pgnd|dgnd|vss)$/i.test(net.trim())) return "0";
    return net.replace(/[^A-Za-z0-9_]/g, "_");
  };
  const netOf = (ref: string, pin: string) => nodeName(nl.netOfPin[`${ref}:${pin}`]);

  const usedModels = new Set<string>();
  for (const inst of schem.symbols) {
    const ref = inst.properties.Reference ?? "?";
    const value = inst.properties.Value ?? "";
    const libId = inst.libId;
    if (libId.startsWith("power:")) continue;

    const a = (p: string) => netOf(ref, p);
    switch (libId) {
      case "Device:R":
        lines.push(`R${ref} ${a("1")} ${a("2")} ${spiceValue(value, "1k")}`);
        break;
      case "Device:C":
      case "Device:C_Polarized":
        lines.push(`C${ref} ${a("1")} ${a("2")} ${spiceValue(value, "100n")}`);
        break;
      case "Device:L":
        lines.push(`L${ref} ${a("1")} ${a("2")} ${spiceValue(value, "10u")}`);
        break;
      case "Device:D":
      case "Device:LED": {
        const model = libId === "Device:LED" ? "DLED" : diodeModelFor(value);
        usedModels.add(model);
        // Pin 1 is the cathode in loon's symbols, pin 2 the anode.
        lines.push(`D${ref} ${a("2")} ${a("1")} ${model}`);
        break;
      }
      case "Device:Q_NMOS_GSD":
        usedModels.add("NMOSSW");
        lines.push(`M${ref} ${a("3")} ${a("1")} ${a("2")} ${a("2")} NMOSSW`);
        break;
      case "Device:Q_NPN_BCE":
        usedModels.add("NPNGEN");
        lines.push(`Q${ref} ${a("2")} ${a("1")} ${a("3")} NPNGEN`);
        break;
      case "Switch:SW_Push":
        // Open by default: a pressed button is a bench stimulus, not a part.
        lines.push(`R${ref}_open ${a("1")} ${a("2")} 1meg`);
        break;
      default:
        unmodelled.push({ ref, libId, reason: "no SPICE model for this part" });
    }
  }

  for (const m of usedModels) {
    if (m === "NMOSSW") lines.push(NMOS_MODEL);
    else if (m === "NPNGEN") lines.push(NPN_MODEL);
    else {
      const entry = Object.entries(DIODE_MODELS).find(([, text]) => text.includes(`.model ${m} `));
      if (entry) lines.push(entry[1]);
    }
  }

  // Sources drive named nets; every rail the design expects needs one, or the
  // simulation runs with the rail floating.
  bench.sources.forEach((src, i) => {
    const n = nodeName(src.net);
    const name = `V${i + 1}_${n}`;
    if (src.kind === "dc") lines.push(`${name} ${n} 0 DC ${src.dc ?? 0}`);
    else if (src.kind === "pulse" && src.pulse) {
      const p = src.pulse;
      lines.push(`${name} ${n} 0 PULSE(${p.v1} ${p.v2} ${p.delay} ${p.rise} ${p.fall} ${p.width} ${p.period})`);
    } else if (src.kind === "sin" && src.sin) {
      lines.push(`${name} ${n} 0 SIN(${src.sin.offset} ${src.sin.amplitude} ${src.sin.freq})`);
    } else if (src.kind === "pwl" && src.pwl) {
      lines.push(`${name} ${n} 0 PWL(${src.pwl.map((p) => `${p.t} ${p.v}`).join(" ")})`);
    }
  });

  for (const extra of bench.extra ?? []) lines.push(extra);

  lines.push(".control");
  if (bench.analysis === "tran") lines.push(`tran ${bench.tranStep ?? 1e-5} ${bench.tranStop ?? 0.05}`);
  else if (bench.analysis === "op") lines.push("op");
  else if (bench.analysis === "dc" && bench.dcSweep)
    lines.push(`dc ${bench.dcSweep.source} ${bench.dcSweep.start} ${bench.dcSweep.stop} ${bench.dcSweep.step}`);
  else if (bench.analysis === "ac" && bench.ac) lines.push(`ac dec ${bench.ac.points} ${bench.ac.start} ${bench.ac.stop}`);

  const probes = bench.probes.map((p) => `v(${nodeName(p)})`).join(" ");
  lines.push(`print ${probes || "all"} > out.txt`);
  lines.push(`wrdata out.csv ${probes}`);
  lines.push("quit");
  lines.push(".endc");
  lines.push(".end");

  return { text: lines.join("\n") + "\n", unmodelled, nets: nl.nets.map((n) => n.name) };
}

// ngspice's wrdata output is columns of "time value time value ...", one pair
// per probe. Turn it into series the UI can plot.
export function parseWrdata(text: string, probes: string[]): { name: string; points: { t: number; v: number }[] }[] {
  const series = probes.map((p) => ({ name: p, points: [] as { t: number; v: number }[] }));
  for (const line of text.split("\n")) {
    const parts = line.trim().split(/\s+/).map(Number);
    if (parts.length < 2 || parts.some((n) => isNaN(n))) continue;
    for (let i = 0; i < series.length; i++) {
      const t = parts[i * 2];
      const v = parts[i * 2 + 1];
      if (t === undefined || v === undefined) continue;
      series[i].points.push({ t, v });
    }
  }
  return series;
}
